name: flutter_reactive_programming
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  rxdart: ^0.27.7
  http: ^0.13.5
  stream_transform: ^2.1.0
  intl: ^0.18.0
  google_mlkit_face_detection: ^0.5.0

  image_picker: ^0.8.7+1
  camera: ^0.10.3+2
  flutter_face_api: ^5.1.3
  dart_either: ^1.0.0

  dio: ^5.0.3
  rx_shared_preferences: ^3.0.0
  rxdart_ext: ^0.2.8

  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0

  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
